name: ${name}
version: ${version}
main: just.plots.JustPlots
author: PureGero
api-version: 1.13
softdepend: [Multiverse-Core, WorldEdit, Essentials]
website: https://github.com/PureGero/JustPlots
commands:
    justplots:
        description: JustPlots command
        aliases: [p, plot, plots, jp, justplot]
