name: JustPlots
version: 0.1.0
main: just.plots.JustPlots
author: PureGero
api-version: 1.13
softdepend: [Multiverse-Core, WorldEdit]
website: https://github.com/PureGero/JustPlots
commands:
    justplots:
        description: JustPlots command
        aliases: [p, plot, plots, jp, justplot]
