name: ${name}
version: ${version}
main: just.plots.JustPlots
author: PureGero
api-version: 1.13
softdepend: [Multiverse-Core, WorldEdit, Essentials]
website: https://github.com/PureGero/JustPlots
commands:
  justplots:
    description: JustPlots command
    aliases: [p, plot, plots, jp, justplot, plotme]
permissions:
  justplots.add:
    description: Add a player to your plot
  justplots.add.other:
    description: Add a player to another player's plot
  justplots.auto:
    description: Claim the next free plot
  justplots.claim:
    description: Claim a plot
  justplots.claim.other:
    description: Claim a plot for another player
  justplots.clear:
    description: Clear a plot
  justplots.clear.other:
    description: Clear another player's plot
  justplots.dispose:
    description: Dispose a plot
  justplots.dispose.other:
    description: Dispose another player's plot
  justplots.edit.other:
    description: Edit another player's plot
  justplots.reset:
    description: Reset a plot
  justplots.reset.other:
    description: Reset another player's plot
  justplots.user:
    description: All the user permissions
    default: true
    children:
      justplots.add: true
      justplots.auto: true
      justplots.claim: true
      justplots.clear: true
      justplots.reset: true
  justplots.admin:
    description: All the admin permissions
    children:
      justplots.add.other: true
      justplots.claim.other: true
      justplots.clear.other: true
      justplots.dispose: true
      justplots.dispose.other: true
      justplots.edit.other: true
      justplots.reset.other: true
      justplots.user: true